### Site Settings ###
title               : "Test"
description         : "DevOps Engineer | Kubernetes 모니터링 솔루션 개발자"
url                 : "https://zzuckerfrei.github.io"
baseurl             : ""

### Author Info ###
author:
  name              : "이선민 (Seonmin Lee)"
  image             : # path of author image
  behance           : 
  dribbble          : 
  email             : "seonmin1219@gmail.com"
  facebook          : 
  github            : "zzuckerfrei"
  gitlab            : 
  instagram         : 
  kaggle            : 
  linkedin          : 
  medium            : 
  soundcloud        : 
  spotify           : 
  stackoverflow     : 
  steam             : 
  tumblr            : 
  twitch            : 
  twitter           : 
  vimeo             : 
  youtube           : 

### Site Settings (2) ###
remote_theme        : "yousinix/portfolYOU"
plugins:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap

paginate            : 4
paginate_path       : "/blog/page:num"
repository          : "zzuckerfrei/zzuckerfrei.github.io"

markdown            : kramdown
highlighter         : rouge
permalink           : /:title/

kramdown:
  input             : GFM
  hard_wrap         : false

sass:
  style             : compressed

collections:
  projects:
    output          : true
    permalink       : /projects/:name/

defaults:
  - scope:
      path          : ""
      type          : "projects"
    values:
      layout        : "page"
  - scope:
      path          : ""
      type          : "posts"
    values:
      layout        : "post"
  - scope:
      path          : ""
    values:
      layout        : "default"

### Exclude ###
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/